Proyecto_SPIEV/SPIEV.WEBSITE/Controllers/RegistroController.cs
using Newtonsoft.Json;
using SPIEV.LIB_WEB;
using SPIEV.REPOS;
using SPIEV.WEBSITE.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web.Mvc;

namespace SPIEV.WEBSITE.Controllers
{
    [SESION_VALIDA]
    [RoutePrefix("registro")]
    public class RegistroController : Controller
    {

        // GET: Registro
        [Route]
        public ActionResult INDEX()
        {
            //DATOS PARA LA VISTA...
            SPIEV_VM MODEL = new SPIEV_VM()
            {
                LISTA_COMUNAS = COMUNA_R.TODAS_COMUNA().ToList(),

                VEHICULO = new VEHICULO_VM()
                {
                    LISTA_TIPOS_COMBUSTIBLE = TIPO_COMBUSTIBLE_VEHICULO_R.TODOS_COMBUSTIBLE().ToList(),
                    LISTA_TIPOS_VEHICULO = TIPO_VEHICULO_R.TODOS_WEB().ToList(),
                    LISTA_TIPOS_MEDIDA = TIPO_MEDIDA_VEHICULO_R.TODOS_TIPOS_MEDIDA().ToList(),
                    LISTA_COLORES_VEHICULO = COLOR_VEHICULO_R.TODOS_COLOR_VEHICULO().ToList(),
                    LISTA_TIPOS_POTENCIA = TIPO_POTENCIA_R.TODOS_TIPO_POTENCIA().ToList(),
                    LISTA_TIPOS_CARROCERIA = TIPO_CARROCERIA_R.TODOS_TIPOS_CARROCERIA().ToList()
                },

                COMUNIDAD = new COMUNIDAD_VM()
                {
                    LISTA_OPCIONES_COMUNIDAD = OPCION_COMUNIDAD_R.TODOS_OPCION_COMUNIDAD().ToList()
                },

                FACTURA = new FACTURA_VM()
                {
                    LISTA_TIPOS_MONEDAS = TIPO_MONEDA_R.TODOS_TIPO_MONEDA().ToList()
                },

                OPERADOR = new OPERADOR_VM()
                {
                    LISTA_REGIONES = REGION_R.TODOS_REGION().ToList()
                },

                SOLICITANTE = new SOLICITANTE_VM()
                {
                    LISTA_CALIDAD_SOLICITANTE = CALIDAD_SOLICITANTE_R.TODOS_CALIDAD_SOLICITANTE().ToList()
                },

                ADQUIRIENTE = new ADQUIRIENTE_VM()
                {
                    LISTA_CALIDAD_ADQUIRIENTE = CALIDAD_ADQUIRIENTE_R.TODOS_CALIDAD_ADQUIRIENTE().ToList()
                },

                ESTIPULANTE = new ESTIPULANTE_VM()
                {
                    LISTA_CALIDAD_ESTIPULANTE = CALIDAD_ESTIPULANTE_R.TODOS_CALIDAD_ESTIPULANTE().ToList()
                }

            };

            //AÑADIR OPCIONES POR DEFECTO...
            //MODEL.VEHICULO.DEFAULT_OPCION();

            return View(MODEL);
        }

        [Route("pagina-inicio")]
        public ActionResult PAGINA_INICIO()
        {
            return View();
        }


        // GET: Registro
        [Route("desde-solicitud/{ID_SOLICITUD:long}")]
        [HttpGet]
        public ActionResult INSCRIPCION_SOLICITUD(long? ID_SOLICITUD)
        {
            //DATOS PARA LA VISTA...
            SPIEV_VM MODEL = new SPIEV_VM()
            {
                ID_SOLICITUD = ID_SOLICITUD,
                LISTA_COMUNAS = COMUNA_R.TODAS_COMUNA().ToList(),

                VEHICULO = new VEHICULO_VM()
                {
                    LISTA_TIPOS_COMBUSTIBLE = TIPO_COMBUSTIBLE_VEHICULO_R.TODOS_COMBUSTIBLE().ToList(),
                    LISTA_TIPOS_VEHICULO = TIPO_VEHICULO_R.TODOS_WEB().ToList(),
                    LISTA_TIPOS_MEDIDA = TIPO_MEDIDA_VEHICULO_R.TODOS_TIPOS_MEDIDA().ToList(),
                    LISTA_COLORES_VEHICULO = COLOR_VEHICULO_R.TODOS_COLOR_VEHICULO().ToList(),
                    LISTA_TIPOS_POTENCIA = TIPO_POTENCIA_R.TODOS_TIPO_POTENCIA().ToList(),
                    LISTA_TIPOS_CARROCERIA = TIPO_CARROCERIA_R.TODOS_TIPOS_CARROCERIA().ToList()
                },

                COMUNIDAD = new COMUNIDAD_VM()
                {
                    LISTA_OPCIONES_COMUNIDAD = OPCION_COMUNIDAD_R.TODOS_OPCION_COMUNIDAD().ToList()
                },

                FACTURA = new FACTURA_VM()
                {
                    LISTA_TIPOS_MONEDAS = TIPO_MONEDA_R.TODOS_TIPO_MONEDA().ToList()
                },

                OPERADOR = new OPERADOR_VM()
                {
                    LISTA_REGIONES = REGION_R.TODOS_REGION().ToList()
                },

                SOLICITANTE = new SOLICITANTE_VM()
                {
                    LISTA_CALIDAD_SOLICITANTE = CALIDAD_SOLICITANTE_R.TODOS_CALIDAD_SOLICITANTE().ToList()
                },

                ADQUIRIENTE = new ADQUIRIENTE_VM()
                {
                    LISTA_CALIDAD_ADQUIRIENTE = CALIDAD_ADQUIRIENTE_R.TODOS_CALIDAD_ADQUIRIENTE().ToList()
                },

                ESTIPULANTE = new ESTIPULANTE_VM()
                {
                    LISTA_CALIDAD_ESTIPULANTE = CALIDAD_ESTIPULANTE_R.TODOS_CALIDAD_ESTIPULANTE().ToList()
                }
            };

            return View(MODEL);
        }

        [HttpPost]
        [Route("guardar-spiev-ajax")]
        public string NUEVO_SPIEV_AJAX(SPIEV_VM MODEL)
        {
            dynamic salida = new ExpandoObject();
            salida.status = false;

            //BLOQUE TRANSACCIONAL PERMITE EL COMMIT, GENERA UN ROLLBACK AUTOMATICO (EN CASO DE EXCEPCION)
            using (System.Transactions.TransactionScope SCOPE = new System.Transactions.TransactionScope())
            {
                try
                {
                    //SI EL MODELO NO ES VALIDO DEVUELVE LA LISTA DE ERRORES
                    if (!ModelState.IsValid) throw new Exception(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).First());

                    //CREAR VEHICULO
                    VEHICULO VEHICULO_CREADO = VEHICULO_R.CREATE(MODEL.VEHICULO.OBJETO_CREAR());

                    //CREAR COMUNIDAD
                    COMUNIDAD COMUNIDAD_CREADA = COMUNIDAD_R.CREATE(MODEL.COMUNIDAD.OBJETO_CREAR());

                    //CREAR ADQUIRIENTE
                    ADQUIRIENTE ADQUIRIENTE_CREADO = ADQUIRIENTE_R.CREATE(MODEL.ADQUIRIENTE.OBJETO_CREAR());

                    //CREAR SOLICITANTE
                    SOLICITANTE SOLICITANTE_CREADO = SOLICITANTE_R.CREATE(MODEL.SOLICITANTE.OBJETO_CREAR());

                    //CREAR ESTIPULANTE
                    ESTIPULANTE ESTIPULANTE_CREADO = ESTIPULANTE_R.CREATE(MODEL.ESTIPULANTE.OBJETO_CREAR());

                    //CREAR IMPUESTO
                    IMPUESTO_ADICIONAL IMPUESTO_CREADO = IMPUESTO_ADICIONAL_R.CREATE(MODEL.IMPUESTO.OBJETO_CREAR());

                    //CREAR FACTURA
                    FACTURA FACTURA_CREADA = FACTURA_R.CREATE(MODEL.FACTURA.OBJETO_CREAR());

                    //CREAR OBSERVACION
                    OBSERVACION OBSERVACION_CREADA = OBSERVACION_R.CREATE(MODEL.OBSERVACION.OBJETO_CREAR());

                    //CREAR OPERADOR
                    OPERADOR OPERADOR_CREADO = OPERADOR_R.CREATE(MODEL.OPERADOR.OBJETO_CREAR());

                    LIB_WEB.SPIEV SPIEV = new LIB_WEB.SPIEV
                    {
                        ID_VEHICULO = VEHICULO_CREADO.ID_VEHICULO,
                        ID_COMUNIDAD = COMUNIDAD_CREADA.ID_COMUNIDAD,
                        ID_SOLICITANTE = SOLICITANTE_CREADO.ID_SOLICITANTE,
                        ID_OBSERVACION = OBSERVACION_CREADA.ID_OBSERVACION,
                        ID_OPERADOR = OPERADOR_CREADO.ID_OPERADOR,
                        FECHA = DateTime.Now
                    };

                    //CREAR SPIEV
                    LIB_WEB.SPIEV SPIEV_CREADO = SPIEV_R.CREATE(SPIEV);

                    //CREAR PRIMERA INSCRIPCION
                    PRIMERA_INSCRIPCION INSCRIPCION_CREADA = PRIMERA_INSCRIPCION_R.CREATE(new PRIMERA_INSCRIPCION
                    {
                        ID_SPIEV = SPIEV_CREADO.ID_SPIEV,
                        ID_ESTADO = 1,
                        ID_USUARIO = SESSION_WEB.SESION_USER.ID_USUARIO,
                        ID_ESTIPULANTE = ESTIPULANTE_CREADO.ID_ESTIPULANTE,
                        ID_ADQUIRIENTE = ADQUIRIENTE_CREADO.ID_ADQUIRIENTE,
                        ID_IMPUESTO_ADICIONAL = IMPUESTO_CREADO.ID_IMPUESTO_ADICIONAL,
                        ID_FACTURA = FACTURA_CREADA.ID_FACTURA,
                    });

                    //SI VIENE DESDE UNA SOLICITUD
                    if (MODEL.ID_SOLICITUD.HasValue)
                    {
                        //ACTUALIZA EL ID DE PRIMERA INSCRIPCION EN LA SOLICITUD (ASOCIA INSCRIPCION CON SOLICITUD)
                        SOLICITUD_SPIEV_R.UPDATE(new SOLICITUD_SPIEV_R.UPDATE_SOLICITUD
                        {
                            ID_SOLICITUD = MODEL.ID_SOLICITUD.Value,
                            ID_ESTADO = 2,
                            ID_PRIMERA_INSCRIPCION = INSCRIPCION_CREADA.ID_PRIMERA_INSCRIPCION,
                        });

                        //GENERA LA HISTORIA SOBRE LA SOLICITUD AL CAMBIAR ESTADO
                        HISTORIA_SOLICITUD_R.CREATE(new HISTORIA_SOLICITUD
                        {
                            ID_SOLICITUD = MODEL.ID_SOLICITUD.Value,
                            ID_ESTADO = 2,
                            ID_USUARIO = SESSION_WEB.SESION_USER.ID_USUARIO,
                            COMENTARIO = "SOLICITUD SPIEV, CON DOCUMENTACIÓN OK",
                            FECHA = DateTime.Now
                        });
                    }

                    //GENERA LA HISTORIA SOBRE LA PRIMERA INSCRIPCIÓN
                    HISTORIA_INSCRIPCION_R.CREATE(new HISTORIA_INSCRIPCION
                    {
                        ID_PRIMERA_INSCRIPCION = INSCRIPCION_CREADA.ID_PRIMERA_INSCRIPCION,
                        ID_ESTADO = 1,
                        ID_USUARIO = SESSION_WEB.SESION_USER.ID_USUARIO,
                        COMENTARIO = "PRIMERA INSCRIPCIÓN, INGRESADA",
                        FECHA = DateTime.Now
                    });

                    //TERMINA LA EJECUCIÓN
                    SCOPE.Complete();

                    //SI TODO SALIO CORRECTO SE ENVIA OK
                    salida.status = true;

Proyecto_SPIEV/SPIEV.WEBSITE/Views/Registro/INDEX.cshtml
@model SPIEV.WEBSITE.Models.SPIEV_VM
<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Formulario de Ingreso</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12" id="alerta-spiev"></div>
                </div>
                <div class="row">
                    <div class="col">
                        <nav>
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                <a class="nav-item nav-link active" id="nav-vehiculo-tab" data-toggle="tab" href="#nav-vehiculo" role="tab" aria-controls="nav-vehiculo" aria-selected="true">
                                    Vehiculo
                                    <span id="vehiculo-load">
                                        <i class="fas fa-spinner fa-spin"></i>
                                    </span>
                                </a>
                                <a class="nav-item nav-link" id="nav-comunidad-tab" data-toggle="tab" href="#nav-comunidad" role="tab" aria-controls="nav-comunidad" aria-selected="false">Comunidad</a>
                                <a class="nav-item nav-link" id="nav-adquiriente-tab" data-toggle="tab" href="#nav-adquiriente" role="tab" aria-controls="nav-adquiriente" aria-selected="false">Adquiriente</a>
                                <a class="nav-item nav-link" id="nav-solicitante-tab" data-toggle="tab" href="#nav-solicitante" role="tab" aria-controls="nav-solicitante" aria-selected="false">Solicitante</a>
                                <a class="nav-item nav-link" id="nav-estipulante-tab" data-toggle="tab" href="#nav-estipulante" role="tab" aria-controls="nav-estipulante" aria-selected="false">Estipulante</a>
                                <a class="nav-item nav-link" id="nav-impuesto-tab" data-toggle="tab" href="#nav-impuesto" role="tab" aria-controls="nav-impuesto" aria-selected="false">Impuesto</a>
                                <a class="nav-item nav-link" id="nav-factura-tab" data-toggle="tab" href="#nav-factura" role="tab" aria-controls="nav-factura" aria-selected="false">Factura</a>
                                <a class="nav-item nav-link" id="nav-observacion-tab" data-toggle="tab" href="#nav-observacion" role="tab" aria-controls="nav-observacion" aria-selected="false">Observacion</a>
                                <a class="nav-item nav-link" id="nav-operador-tab" data-toggle="tab" href="#nav-operador" role="tab" aria-controls="nav-operador" aria-selected="false">Operador</a>
                            </div>
                        </nav>
                        <div class="tab-content" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-vehiculo" role="tabpanel" aria-labelledby="nav-comunidad-tab">
                                @Html.Partial("~/Views/Shared/Inscripcion/_VehiculoForm.cshtml", Model)
                            </div>
                            <div class="tab-pane fade" id="nav-comunidad" role="tabpanel" aria-labelledby="nav-comunidad-tab">
                                @Html.Partial("~/Views/Shared/Inscripcion/_ComunidadForm.cshtml", Model)
                            </div>
                            <div class="tab-pane fade" id="nav-adquiriente" role="tabpanel" aria-labelledby="nav-adquiriente-tab">
                                @Html.Partial("~/Views/Shared/Inscripcion/_AdquirienteForm.cshtml", Model)
                            </div>
                            <div class="tab-pane fade" id="nav-solicitante" role="tabpanel" aria-labelledby="nav-contact-tab">
                                @Html.Partial("~/Views/Shared/Inscripcion/_SolicitanteForm.cshtml", Model)
                            </div>
                            <div id="nav-estipulante" role="tabpanel" class="tab-pane fade">
                                @Html.Partial("~/Views/Shared/Inscripcion/_EstipulanteForm.cshtml", Model)
                            </div>
                            <div id="nav-impuesto" role="tabpanel" class="tab-pane fade">
                                @Html.Partial("~/Views/Shared/Inscripcion/_ImpuestoForm.cshtml", Model)
                            </div>
                            <div id="nav-factura" role="tabpanel" class="tab-pane fade">
                                @Html.Partial("~/Views/Shared/Inscripcion/_FacturaForm.cshtml", Model)
                            </div>
                            <div id="nav-observacion" role="tabpanel" class="tab-pane fade">
                                @Html.Partial("~/Views/Shared/Inscripcion/_ObservacionForm.cshtml", Model)
                            </div>
                            <div id="nav-operador" role="tabpanel" class="tab-pane fade">
                                @Html.Partial("~/Views/Shared/Inscripcion/_OperadorForm.cshtml", Model)

                                <div class="p-3">
                                    <div class="col-xs-12">
                                        <div class="text-right">
                                            <button id="btn-generar-spiev" class="btn btn-success" type="button">
                                                Generar 1era Inscripción
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--RENDERIZADO DE ESTILOS POR PAGINA-->
@section styles
{
    @Styles.Render("~/Content/bootstrap-datepicker/bootstrap-datepicker3.min.css")
    @Styles.Render("~/Content/select2/select2.min.css")
}

<!--RENDERIZADO DE SCRIPTS POR PAGINA-->
@section scripts
{
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker/bootstrap-datepicker.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker/bootstrap-datepicker.es.min.js")
    @Scripts.Render("~/Scripts/select2/select2.min.js")
    @Scripts.Render($"~/Scripts/pages/Registro_Index.js?v={DateTime.Now.ToString("ddMMyyyyHmm")}")

    <script>
        $('#VEHICULO_AGNO_FABRICACION').datepicker({
            language: 'es',
            autoclose: true,
            startDate: '-20y',
            endDate: new Date(),
            format: "yyyy",
            viewMode: "years",
            minViewMode: "years"
        });

        $('#FACTURA_FECHA').datepicker({
            language: 'es',
            autoclose: true,
            endDate: new Date(),
            format: 'yyyymmdd',
        });

        $('.select2').select2({
            width: '100%'
        });
    </script>
}

Proyecto_SPIEV/SPIEV.WEBSITE/Views/Registro/PAGINA_INICIO.cshtml
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bienvenido, Portal Primeras Inscripciones</h1>
</div>

<!-- Content Row -->
<div class="row row-eq-height">

    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card bg-dark text-white h-100">
            <img class="card-img caja-landing-solicitud h-100" src="~/Images/InicioSolicitud/caluga-solicitud.jpg" alt="Card image">
            <div class="card-img-overlay">
                <h5 class="card-title font-weight-bold text-white transparencia-landing-solicitud">Solicitudes Ingresadas</h5>
                <p class="card-text transparencia-landing-solicitud">Solicitudes recibidas y pendientes</p>
                <a href="@Url.Action("SOLICITUD_INGRESO","Registro")" class="btn btn-outline-light">Ir a la opción</a>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card bg-dark text-white h-100">
            <img class="card-img caja-landing-solicitud h-100" src="~/Images/InicioSolicitud/caluga-transferencia.jpg" alt="Card image">
            <div class="card-img-overlay">
                <h5 class="card-title font-weight-bold text-white transparencia-landing-solicitud">Inscripciones Realizadas</h5>
                <p class="card-text transparencia-landing-solicitud">Todas las inscripciones generadas por usuario</p>
                <a href="@Url.Action("INSCRIPCION_INGRESO","Inscripcion")" class="btn btn-outline-light">Ir a la opción</a>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card bg-dark text-white h-100">
            <img class="card-img caja-landing-solicitud h-100" src="~/Images/InicioSolicitud/caluga-reporte.jpg" alt="Card image">
            <div class="card-img-overlay">
                <h5 class="card-title font-weight-bold text-white transparencia-landing-solicitud">Gestión Rechazos</h5>
                <p class="card-text transparencia-landing-solicitud">Inscripciones rechazadas por SPIEV</p>
                <a href="@Url.Action("INSCRIPCION_RECHAZO","Inscripcion")" class="btn btn-outline-light">Ir a la opción</a>
            </div>
        </div>
    </div>

</div>

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h6 class="h5 mb-0 text-gray-800">Resumen de Inscripciones</h6>
</div>

<div class="row">

    <div class="col mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Solicitudes Ingresadas</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800 ">
                            <span id="total-solicitud-ingresada" class="integers">0</span>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-newspaper fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Inscripciones Ingresadas</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800 ">
                            <span id="total-inscripcion-ingresada" class="integers">0</span>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-check-double fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Inscripciones Rechazadas</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <span id="total-inscripcion-rechazada" class="integers">0</span>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-exclamation-triangle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Documentación Cargada</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <span id="total-inscripcion-cargada" class="integers">0</span>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-file-upload fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total de Inscripciones</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <span id="total-inscripcion" class="integers">0</span>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-chart-pie fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Content Row -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Estadisticas por estado:</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Opciones</div>
                        <a class="dropdown-item" href="#">Recargar</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area">
                    <div id="chartdiv" style="width: 100%; height: 300px; background-color: #FFFFFF;"></div>
                </div>
            </div>
        </div>
    </div>


<!--RENDERIZADO DE SCRIPTS POR PAGINA-->
@section scripts
{
    <!--Contador JQUERY-->
    @Scripts.Render("~/Scripts/counter-up/jquery.counterup.min.js")
    @Scripts.Render("~/Scripts/counter-up/jquery.waypoints.js")

    <!--GRAFICOS-->
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/pie.js"></script>

    @Scripts.Render($"~/Scripts/pages/Registro_Pagina_Inicio.js?v={DateTime.Now.ToString("ddMMyyyyHmm")}")
}